
POST http://localhost:5000/createToken
Content-Type: application/json

{
    "id": "1",
    "name": "omar",
    "password" : "1234",
    "role" : "admin"

}

###
GET http://localhost:5000/users
// Admin
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJuYW1lIjoiRmFobWkiLCJlbWFpbCI6IkZhaG1pQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMzY5NiIsInBob25lIjoiMDc4ODAwMDAwMCIsImFkZHJlc3MiOiJBbW1hbiIsImlhdCI6MTY4NTcyNTgzMH0.PlS6Q5KmtkVx5_OO8_dSR0yJ4Uc8SHk007OOvsbSdFI
// Provider
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicHJvdmlkZXIiLCJuYW1lIjoiT2JpZGEiLCJlbWFpbCI6Ik9iaWRhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMzY5NiIsInBob25lIjoiMDc4ODAwMDAwMCIsImFkZHJlc3MiOiJBbW1hbiIsImlhdCI6MTY4NTcyNTk2MH0.buFJxWAnERDT8fQW44bV97VUho7Il8HbAsNlfsOusUE
// Provider
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsIm5hbWUiOiJBYmVkIiwiZW1haWwiOiJBYmVkQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMzY5NiIsInBob25lIjoiMDc4ODAwMDAwMCIsImFkZHJlc3MiOiJBbW1hbiIsImlhdCI6MTY4NTcyNjAyN30.NZ3RVr2TmWgAthwV2VBN1u1cRh04NQYGGdKWJYnTKOA

###
GET http://localhost:5000/users
