
POST http://localhost:5000/createToken
Content-Type: application/json

{
    "id": "1",
    "name": "omar",
    "password" : "1234",
    "role" : "admin"

}

###
GET http://localhost:5000/users
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJuYW1lIjoib21hciIsInBhc3N3b3JkIjoiMTIzNCIsImlhdCI6MTY4NTQ1NjQyMCwiZXhwIjoxNjg1ODg4NDIwfQ.96EBN7qdOuLsWqC2KhIxZ51vzz3-zLwI1fyKzmRT4tQ
